container_image = TBD

executable  = example.py
arguments    = $(station_id)

transfer_input_files = scripts/, osdf:///aws-opendata/us-east-1/noaa-ghcn-pds/csv/by_station/$(station_id).csv

log          = logs/example.$(Cluster).log
output       = logs/$(station_id).out
error        = logs/$(station_id).err

request_cpus   = 1
request_memory = 4GB
request_disk   = 4GB

queue station_id from station_list.txt
